SELECT *
FROM dbo.AUDITORIUM
FULL OUTER JOIN dbo.AUDITORIUM_TYPE
ON dbo.AUDITORIUM.AUDITORIUM_TYPE = dbo.AUDITORIUM_TYPE.AUDITORIUM_TYPE
WHERE dbo.AUDITORIUM.AUDITORIUM_TYPE IS NULL;

SELECT *
FROM dbo.AUDITORIUM FULL OUTER JOIN dbo.AUDITORIUM_TYPE
ON dbo.AUDITORIUM.AUDITORIUM_TYPE = dbo.AUDITORIUM_TYPE.AUDITORIUM_TYPE
WHERE AUDITORIUM_TYPE.AUDITORIUM_TYPE is NULL


SELECT *
FROM dbo.AUDITORIUM FULL OUTER JOIN dbo.AUDITORIUM_TYPE
ON dbo.AUDITORIUM.AUDITORIUM_TYPE = dbo.AUDITORIUM_TYPE.AUDITORIUM_TYPE
WHERE AUDITORIUM.AUDITORIUM_TYPE is NOT NULL 

use Бычок_MyBase
select *
from Группа FULL outer join Курсы
on Группа.Номер_группы = Курсы.Номер_группы
where Курсы.Количество_часов is null